### ISSUE TITLE
Use custom config file for settings

### ISSUE THREAD

**Issue by Morgy93** [dermatz/ddev-woodoo-buildtools-magento#15]
If you execute any DDEV action that alters the config.yaml, the custom `themes` setting will be removed.

To prevent this from happening a custom config file should be used.

**Comment by rfay** [comment]
@Morgy93 could you say more? `ddev config` will not discard things from the config.yaml unless they don't belong there. What's going on specifically?

**Comment by Morgy93** [comment]
@rfay After executing `ddev debug migrate-database mariadb:10.6` it updated the whole `config.yaml` and even removed the `themes` setting which is written by this addon.

**Comment by rfay** [comment]
So if you're using a key in the yaml that is not supported by DDEV... you shouldn't be. You're using `themes:` in config.yaml? It doesn't belong there. You'd want to have your own config.yaml for it. The keys that are supported are listed in the comments section or in DDEV's definition of the struct/yaml.
