### ISSUE TITLE
Ask for theme path during install

### ISSUE THREAD

**Issue by Morgy93** [dermatz/ddev-woodoo-buildtools-magento#16]
During frontend install you're asked which themes to add.

Afterwards you must edit the theme paths in config.yaml manually.

It would be great if you could enter the path during the install.

**Comment by dermatz** [comment]
We can do it optional. 
If you write a src path during the installation, then we can write it to the config file.

**Comment by dermatz** [comment]
We found a solution to handle this in a new way. This feature will be released in 1.4.0
