### ISSUE TITLE
Warn if a "frontend" command exist during installation

### ISSUE THREAD

**Issue by dermatz** [dermatz/ddev-woodoo-buildtools-magento#25]
Could not run/install command ddev frontend init if "frontend" command already exists.

**Comment by Morgy93** [comment]
It throws the error:

```
NOT overwriting .ddev/commands/web/frontend.
The #ddev-generated signature was not found in the file, so it will not be overwritten.
You can remove the file and use DDEV get again if you want it to be replaced: signature was not found in file .ddev/commands/web/frontend 
```

So it's by design and I think we should not interfere with it. 😕

**Comment by rfay** [comment]
Apparently the `frontend` has been modified by the user, since the original has `#ddev-generated` in it:

https://github.com/dermatz/ddev-woodoo-buildtools-magento/blob/main/commands/web/frontend#L2

So if you don't care about the modifications, just remove that file and a `ddev get` will work without errors.

**Comment by dermatz** [comment]
In the agency environment, it has happened now and again that some developers have built their own frontend command, which now clashes with ours. So my plan is to check in advance and tell the user that such a file exists and to overwrite it directly if necessary, even if there is no `#ddev-generated`.

**Comment by dermatz** [comment]
> It throws the error:
> 
> ```
> NOT overwriting .ddev/commands/web/frontend.
> The #ddev-generated signature was not found in the file, so it will not be overwritten.
> You can remove the file and use DDEV get again if you want it to be replaced: signature was not found in file .ddev/commands/web/frontend 
> ```
> 
> So it's by design and I think we should not interfere with it. 😕

Yes, I'm fine with that. All needed information about the case are given during the installation. 
The user just needs to use his eyes.

I will close this ticket and PR right now.
