### ISSUE TITLE
Evaluate Aliases Annotation support

### ISSUE THREAD

**Issue by Morgy93** [dermatz/ddev-woodoo-buildtools-magento#34]
https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#aliases-annotation

ChatGPT suggestions:

ddev fe
ddev front
ddev fnt
ddev fr
ddev fe-dev
ddev front-dev
ddev fd
ddev fe-cli
ddev fcli
ddev fe-run

**Comment by dermatz** [comment]
Sounds good.

i perfer these both:

- ddev f
- ddev fe

**Comment by Morgy93** [comment]
Implemented via #35 

Closed~
