### ISSUE TITLE
CLI Video of the Init-Command to improve readme.md

### ISSUE THREAD

**Issue by dermatz** [dermatz/ddev-woodoo-buildtools-magento#37]
To help interested people better understand what woodoo actually is, a video of the CLI will introduce the process and be placed as a GIF video in the `README.MD`.

**Comment by Morgy93** [comment]
There's an example at https://github.com/charmbracelet/gum/blob/main/README.md
They have a GIF demo for every command.

Even though I don't like (long) GIF demos because you are not able to follow at your own pace.
At least GitHub has a pause feature now for GIFs. That's nice.

**Comment by dermatz** [comment]
The goal is not to create a documentation with a gif, but to show that the tool uses an intuitive way to manage and build themes. I think it should not take longer than 10 seconds
